//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pb_HashTag
    {
        public pb_HashTag()
        {
            this.pb_ProductTag = new HashSet<pb_ProductTag>();
        }
    
        public System.Guid HashTagId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public byte Type { get; set; }
        public string TagName { get; set; }
        public string IconPath { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string TextName { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual pb_UserProfile pb_UserProfile { get; set; }
        public virtual ICollection<pb_ProductTag> pb_ProductTag { get; set; }
    }
}
