//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pb_Order
    {
        public System.Guid OrderId { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public double Price { get; set; }
        public byte Amount { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public byte Status { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual pb_Product pb_Product { get; set; }
        public virtual pb_UserProfile pb_UserProfile { get; set; }
    }
}
