//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pb_Photo
    {
        public System.Guid PhotoId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public string ImagePath { get; set; }
        public byte Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ImageW1 { get; set; }
        public string ImageH1 { get; set; }
        public string ImageH2 { get; set; }
    
        public virtual pb_UserProfile pb_UserProfile { get; set; }
        public virtual pb_Product pb_Product { get; set; }
    }
}
