//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pb_UserContact
    {
        public System.Guid UserContactId { get; set; }
        public System.Guid UserId { get; set; }
        public int ContactTypeId { get; set; }
        public string ContactName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual pb_ContactType pb_ContactType { get; set; }
        public virtual pb_UserProfile pb_UserProfile { get; set; }
    }
}
