//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pb_UserProfile
    {
        public pb_UserProfile()
        {
            this.pb_Comment = new HashSet<pb_Comment>();
            this.pb_HashTag = new HashSet<pb_HashTag>();
            this.pb_Location = new HashSet<pb_Location>();
            this.pb_Photo = new HashSet<pb_Photo>();
            this.pb_ProductTag = new HashSet<pb_ProductTag>();
            this.pb_UserContact = new HashSet<pb_UserContact>();
            this.pb_Order = new HashSet<pb_Order>();
            this.pb_Product = new HashSet<pb_Product>();
        }
    
        public System.Guid UserId { get; set; }
        public int MembershipId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Avatar { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<pb_Comment> pb_Comment { get; set; }
        public virtual ICollection<pb_HashTag> pb_HashTag { get; set; }
        public virtual ICollection<pb_Location> pb_Location { get; set; }
        public virtual ICollection<pb_Photo> pb_Photo { get; set; }
        public virtual ICollection<pb_ProductTag> pb_ProductTag { get; set; }
        public virtual ICollection<pb_UserContact> pb_UserContact { get; set; }
        public virtual ICollection<pb_Order> pb_Order { get; set; }
        public virtual ICollection<pb_Product> pb_Product { get; set; }
    }
}
