//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbData.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class pb_Entities : DbContext
    {
        public pb_Entities()
            : base("name=pb_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<pb_Comment> pb_Comment { get; set; }
        public DbSet<pb_ContactType> pb_ContactType { get; set; }
        public DbSet<pb_HashTag> pb_HashTag { get; set; }
        public DbSet<pb_Location> pb_Location { get; set; }
        public DbSet<pb_Photo> pb_Photo { get; set; }
        public DbSet<pb_ProductTag> pb_ProductTag { get; set; }
        public DbSet<pb_UserContact> pb_UserContact { get; set; }
        public DbSet<pb_UserProfile> pb_UserProfile { get; set; }
        public DbSet<pb_Product> pb_Product { get; set; }
        public DbSet<pb_Order> pb_Order { get; set; }
        public DbSet<pb_Reference> pb_Reference { get; set; }
    
        public virtual ObjectResult<Nullable<int>> pb_Comment_Create(Nullable<System.Guid> commentId, Nullable<System.Guid> productId, Nullable<System.Guid> userId, string comment)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("commentId", commentId) :
                new ObjectParameter("commentId", typeof(System.Guid));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Comment_Create", commentIdParameter, productIdParameter, userIdParameter, commentParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Comment_Delete(Nullable<System.Guid> commentId)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("commentId", commentId) :
                new ObjectParameter("commentId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Comment_Delete", commentIdParameter);
        }
    
        public virtual ObjectResult<pb_Comment> pb_Comment_GetbyProductId(Nullable<System.Guid> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Comment>("pb_Comment_GetbyProductId", productIdParameter);
        }
    
        public virtual ObjectResult<pb_Comment> pb_Comment_GetbyProductId(Nullable<System.Guid> productId, MergeOption mergeOption)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Comment>("pb_Comment_GetbyProductId", mergeOption, productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_HashTag_Create(Nullable<System.Guid> hashTagId, Nullable<System.Guid> userId, Nullable<byte> type, string textName, string tagName, string iconPath, string description)
        {
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(byte));
    
            var textNameParameter = textName != null ?
                new ObjectParameter("textName", textName) :
                new ObjectParameter("textName", typeof(string));
    
            var tagNameParameter = tagName != null ?
                new ObjectParameter("tagName", tagName) :
                new ObjectParameter("tagName", typeof(string));
    
            var iconPathParameter = iconPath != null ?
                new ObjectParameter("iconPath", iconPath) :
                new ObjectParameter("iconPath", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_HashTag_Create", hashTagIdParameter, userIdParameter, typeParameter, textNameParameter, tagNameParameter, iconPathParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_HashTag_Delete(Nullable<System.Guid> hashTagId)
        {
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_HashTag_Delete", hashTagIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_HashTag_Update(Nullable<System.Guid> hashTagId, Nullable<byte> type, string iconPath, string description)
        {
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(byte));
    
            var iconPathParameter = iconPath != null ?
                new ObjectParameter("iconPath", iconPath) :
                new ObjectParameter("iconPath", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_HashTag_Update", hashTagIdParameter, typeParameter, iconPathParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Location_Create(Nullable<System.Guid> locationId, Nullable<System.Guid> userId, Nullable<double> latitude, Nullable<double> longitude, string address)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Location_Create", locationIdParameter, userIdParameter, latitudeParameter, longitudeParameter, addressParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Location_Delete(Nullable<System.Guid> locationId)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Location_Delete", locationIdParameter);
        }
    
        public virtual ObjectResult<pb_Location> pb_Location_GetbyId(Nullable<System.Guid> locationId)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Location>("pb_Location_GetbyId", locationIdParameter);
        }
    
        public virtual ObjectResult<pb_Location> pb_Location_GetbyId(Nullable<System.Guid> locationId, MergeOption mergeOption)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Location>("pb_Location_GetbyId", mergeOption, locationIdParameter);
        }
    
        public virtual ObjectResult<pb_Location> pb_Location_GetbyUserId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Location>("pb_Location_GetbyUserId", userIdParameter);
        }
    
        public virtual ObjectResult<pb_Location> pb_Location_GetbyUserId(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Location>("pb_Location_GetbyUserId", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Location_Update(Nullable<System.Guid> locationId, Nullable<double> latitude, Nullable<double> longitude, string address)
        {
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(System.Guid));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Location_Update", locationIdParameter, latitudeParameter, longitudeParameter, addressParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Photo_Create(Nullable<System.Guid> photoId, Nullable<System.Guid> userId, Nullable<System.Guid> productId, string imagePath)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var imagePathParameter = imagePath != null ?
                new ObjectParameter("imagePath", imagePath) :
                new ObjectParameter("imagePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Photo_Create", photoIdParameter, userIdParameter, productIdParameter, imagePathParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Photo_Delete(Nullable<System.Guid> photoId)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Photo_Delete", photoIdParameter);
        }
    
        public virtual ObjectResult<pb_Photo> pb_Photo_GetbyId(Nullable<System.Guid> photoId)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Photo>("pb_Photo_GetbyId", photoIdParameter);
        }
    
        public virtual ObjectResult<pb_Photo> pb_Photo_GetbyId(Nullable<System.Guid> photoId, MergeOption mergeOption)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Photo>("pb_Photo_GetbyId", mergeOption, photoIdParameter);
        }
    
        public virtual ObjectResult<pb_Photo> pb_Photo_GetbyProductId(Nullable<System.Guid> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Photo>("pb_Photo_GetbyProductId", productIdParameter);
        }
    
        public virtual ObjectResult<pb_Photo> pb_Photo_GetbyProductId(Nullable<System.Guid> productId, MergeOption mergeOption)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Photo>("pb_Photo_GetbyProductId", mergeOption, productIdParameter);
        }
    
        internal virtual ObjectResult<Nullable<int>> pb_Product_Create(Nullable<System.Guid> productId, Nullable<System.Guid> userId, string name, Nullable<double> price, string description, string humanCode)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(double));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var humanCodeParameter = humanCode != null ?
                new ObjectParameter("humanCode", humanCode) :
                new ObjectParameter("humanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Product_Create", productIdParameter, userIdParameter, nameParameter, priceParameter, descriptionParameter, humanCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Product_Delete(Nullable<System.Guid> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Product_Delete", productIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyId(Nullable<System.Guid> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyId", productIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyId(Nullable<System.Guid> productId, MergeOption mergeOption)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyId", mergeOption, productIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyUserId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyUserId", userIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyUserId(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyUserId", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Product_Update(Nullable<System.Guid> productId, string name, Nullable<double> price, string description)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(double));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Product_Update", productIdParameter, nameParameter, priceParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_ProductTag_Create(Nullable<System.Guid> productTagId, Nullable<System.Guid> productId, Nullable<System.Guid> hashTagId, Nullable<System.Guid> userId, string comment)
        {
            var productTagIdParameter = productTagId.HasValue ?
                new ObjectParameter("productTagId", productTagId) :
                new ObjectParameter("productTagId", typeof(System.Guid));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_ProductTag_Create", productTagIdParameter, productIdParameter, hashTagIdParameter, userIdParameter, commentParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_ProductTag_Delete(Nullable<System.Guid> productTagId)
        {
            var productTagIdParameter = productTagId.HasValue ?
                new ObjectParameter("productTagId", productTagId) :
                new ObjectParameter("productTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_ProductTag_Delete", productTagIdParameter);
        }
    
        public virtual ObjectResult<pb_ProductTag> pb_ProductTag_GetbyHashTagId(Nullable<System.Guid> hashTagId, Nullable<System.Guid> productId)
        {
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_ProductTag>("pb_ProductTag_GetbyHashTagId", hashTagIdParameter, productIdParameter);
        }
    
        public virtual ObjectResult<pb_ProductTag> pb_ProductTag_GetbyHashTagId(Nullable<System.Guid> hashTagId, Nullable<System.Guid> productId, MergeOption mergeOption)
        {
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_ProductTag>("pb_ProductTag_GetbyHashTagId", mergeOption, hashTagIdParameter, productIdParameter);
        }
    
        public virtual ObjectResult<pb_ProductTag> pb_ProductTag_GetbyProductId(Nullable<System.Guid> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_ProductTag>("pb_ProductTag_GetbyProductId", productIdParameter);
        }
    
        public virtual ObjectResult<pb_ProductTag> pb_ProductTag_GetbyProductId(Nullable<System.Guid> productId, MergeOption mergeOption)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_ProductTag>("pb_ProductTag_GetbyProductId", mergeOption, productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_UserContact_Create(Nullable<System.Guid> userContactId, Nullable<System.Guid> userId, Nullable<int> contactTypeId, string contactName)
        {
            var userContactIdParameter = userContactId.HasValue ?
                new ObjectParameter("userContactId", userContactId) :
                new ObjectParameter("userContactId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var contactTypeIdParameter = contactTypeId.HasValue ?
                new ObjectParameter("contactTypeId", contactTypeId) :
                new ObjectParameter("contactTypeId", typeof(int));
    
            var contactNameParameter = contactName != null ?
                new ObjectParameter("contactName", contactName) :
                new ObjectParameter("contactName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_UserContact_Create", userContactIdParameter, userIdParameter, contactTypeIdParameter, contactNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_UserContact_Delete(Nullable<System.Guid> userContactId)
        {
            var userContactIdParameter = userContactId.HasValue ?
                new ObjectParameter("userContactId", userContactId) :
                new ObjectParameter("userContactId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_UserContact_Delete", userContactIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_UserContact_Update(Nullable<System.Guid> userContactId, Nullable<int> contactTypeId, string contactName)
        {
            var userContactIdParameter = userContactId.HasValue ?
                new ObjectParameter("userContactId", userContactId) :
                new ObjectParameter("userContactId", typeof(System.Guid));
    
            var contactTypeIdParameter = contactTypeId.HasValue ?
                new ObjectParameter("contactTypeId", contactTypeId) :
                new ObjectParameter("contactTypeId", typeof(int));
    
            var contactNameParameter = contactName != null ?
                new ObjectParameter("contactName", contactName) :
                new ObjectParameter("contactName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_UserContact_Update", userContactIdParameter, contactTypeIdParameter, contactNameParameter);
        }
    
        public virtual int pb_UserProfile_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pb_UserProfile_GetAll");
        }
    
        public virtual ObjectResult<pb_UserProfile> pb_UserProfile_GetbyId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_UserProfile>("pb_UserProfile_GetbyId", userIdParameter);
        }
    
        public virtual ObjectResult<pb_UserProfile> pb_UserProfile_GetbyId(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_UserProfile>("pb_UserProfile_GetbyId", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<pb_UserProfile> pb_UserProfile_GetbyUserName(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_UserProfile>("pb_UserProfile_GetbyUserName", userNameParameter);
        }
    
        public virtual ObjectResult<pb_UserProfile> pb_UserProfile_GetbyUserName(string userName, MergeOption mergeOption)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_UserProfile>("pb_UserProfile_GetbyUserName", mergeOption, userNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_UserProfile_Update(Nullable<System.Guid> userId, string firstName, string lastName, Nullable<System.DateTime> dateOfBirth)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var dateOfBirthParameter = dateOfBirth.HasValue ?
                new ObjectParameter("dateOfBirth", dateOfBirth) :
                new ObjectParameter("dateOfBirth", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_UserProfile_Update", userIdParameter, firstNameParameter, lastNameParameter, dateOfBirthParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Product_UpdateDiscountPrice(Nullable<System.Guid> productId, Nullable<double> discountPrice)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var discountPriceParameter = discountPrice.HasValue ?
                new ObjectParameter("discountPrice", discountPrice) :
                new ObjectParameter("discountPrice", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Product_UpdateDiscountPrice", productIdParameter, discountPriceParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Photo_UpdateProductId(Nullable<System.Guid> photoId, Nullable<System.Guid> productId)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Photo_UpdateProductId", photoIdParameter, productIdParameter);
        }
    
        public virtual ObjectResult<pb_HashTag> pb_HashTag_GetbyTagName(string tagName)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("tagName", tagName) :
                new ObjectParameter("tagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_HashTag>("pb_HashTag_GetbyTagName", tagNameParameter);
        }
    
        public virtual ObjectResult<pb_HashTag> pb_HashTag_GetbyTagName(string tagName, MergeOption mergeOption)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("tagName", tagName) :
                new ObjectParameter("tagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_HashTag>("pb_HashTag_GetbyTagName", mergeOption, tagNameParameter);
        }
    
        public virtual ObjectResult<pb_UserContact> pb_UserContact_GetbyUserId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_UserContact>("pb_UserContact_GetbyUserId", userIdParameter);
        }
    
        public virtual ObjectResult<pb_UserContact> pb_UserContact_GetbyUserId(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_UserContact>("pb_UserContact_GetbyUserId", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<pb_HashTag> pb_HashTag_GetbyProductId(Nullable<System.Guid> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_HashTag>("pb_HashTag_GetbyProductId", productIdParameter);
        }
    
        public virtual ObjectResult<pb_HashTag> pb_HashTag_GetbyProductId(Nullable<System.Guid> productId, MergeOption mergeOption)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_HashTag>("pb_HashTag_GetbyProductId", mergeOption, productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_UserProfile_UpdateAvatar(Nullable<System.Guid> userId, string avatar)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var avatarParameter = avatar != null ?
                new ObjectParameter("avatar", avatar) :
                new ObjectParameter("avatar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_UserProfile_UpdateAvatar", userIdParameter, avatarParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Order_Create(Nullable<System.Guid> orderId, Nullable<System.Guid> productId, Nullable<System.Guid> userId, string customerName, string customerPhone, Nullable<double> price, Nullable<byte> amount, string address, string comment)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(System.Guid));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("customerName", customerName) :
                new ObjectParameter("customerName", typeof(string));
    
            var customerPhoneParameter = customerPhone != null ?
                new ObjectParameter("customerPhone", customerPhone) :
                new ObjectParameter("customerPhone", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(double));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(byte));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Order_Create", orderIdParameter, productIdParameter, userIdParameter, customerNameParameter, customerPhoneParameter, priceParameter, amountParameter, addressParameter, commentParameter);
        }
    
        public virtual ObjectResult<pb_Order> pb_Order_GetbySalesman(Nullable<System.Guid> userId, Nullable<byte> status)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Order>("pb_Order_GetbySalesman", userIdParameter, statusParameter);
        }
    
        public virtual ObjectResult<pb_Order> pb_Order_GetbySalesman(Nullable<System.Guid> userId, Nullable<byte> status, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Order>("pb_Order_GetbySalesman", mergeOption, userIdParameter, statusParameter);
        }
    
        public virtual ObjectResult<pb_Order> pb_Order_GetbyUserId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Order>("pb_Order_GetbyUserId", userIdParameter);
        }
    
        public virtual ObjectResult<pb_Order> pb_Order_GetbyUserId(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Order>("pb_Order_GetbyUserId", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Order_UpdateStatus(Nullable<System.Guid> orderId, Nullable<byte> status)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Order_UpdateStatus", orderIdParameter, statusParameter);
        }
    
        public virtual ObjectResult<pb_HashTag> tp_HashTag_GetbyUserId(Nullable<System.Guid> userId, Nullable<byte> type)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_HashTag>("tp_HashTag_GetbyUserId", userIdParameter, typeParameter);
        }
    
        public virtual ObjectResult<pb_HashTag> tp_HashTag_GetbyUserId(Nullable<System.Guid> userId, Nullable<byte> type, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_HashTag>("tp_HashTag_GetbyUserId", mergeOption, userIdParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_ProductTag_DeleteByProductId(Nullable<System.Guid> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_ProductTag_DeleteByProductId", productIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyHashTagId(Nullable<System.Guid> hashTagId)
        {
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyHashTagId", hashTagIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyHashTagId(Nullable<System.Guid> hashTagId, MergeOption mergeOption)
        {
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyHashTagId", mergeOption, hashTagIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyUserAndTag(Nullable<System.Guid> userId, Nullable<System.Guid> hashTagId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyUserAndTag", userIdParameter, hashTagIdParameter);
        }
    
        public virtual ObjectResult<pb_Product> pb_Product_GetbyUserAndTag(Nullable<System.Guid> userId, Nullable<System.Guid> hashTagId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Product>("pb_Product_GetbyUserAndTag", mergeOption, userIdParameter, hashTagIdParameter);
        }
    
        public virtual ObjectResult<pb_ProductTag> pb_ProductTag_GetbyUserAndTag(Nullable<System.Guid> productId, Nullable<System.Guid> userId, Nullable<System.Guid> hashTagId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_ProductTag>("pb_ProductTag_GetbyUserAndTag", productIdParameter, userIdParameter, hashTagIdParameter);
        }
    
        public virtual ObjectResult<pb_ProductTag> pb_ProductTag_GetbyUserAndTag(Nullable<System.Guid> productId, Nullable<System.Guid> userId, Nullable<System.Guid> hashTagId, MergeOption mergeOption)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var hashTagIdParameter = hashTagId.HasValue ?
                new ObjectParameter("hashTagId", hashTagId) :
                new ObjectParameter("hashTagId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_ProductTag>("pb_ProductTag_GetbyUserAndTag", mergeOption, productIdParameter, userIdParameter, hashTagIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Reference_Create(string name, string value)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Reference_Create", nameParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Reference_Delete(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Reference_Delete", nameParameter);
        }
    
        public virtual ObjectResult<pb_Reference> pb_Reference_GetByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Reference>("pb_Reference_GetByName", nameParameter);
        }
    
        public virtual ObjectResult<pb_Reference> pb_Reference_GetByName(string name, MergeOption mergeOption)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pb_Reference>("pb_Reference_GetByName", mergeOption, nameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Reference_Update(string name, string value)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Reference_Update", nameParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Product_UpdateStatus(Nullable<System.Guid> productId, Nullable<int> status)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Product_UpdateStatus", productIdParameter, statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Product_UpdateHumanCode(Nullable<System.Guid> productId, string humanCode)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(System.Guid));
    
            var humanCodeParameter = humanCode != null ?
                new ObjectParameter("humanCode", humanCode) :
                new ObjectParameter("humanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Product_UpdateHumanCode", productIdParameter, humanCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Photo_UpdateStatus(Nullable<System.Guid> photoId, Nullable<byte> status)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Photo_UpdateStatus", photoIdParameter, statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Photo_UpdateImageH1(Nullable<System.Guid> photoId, string imageH1)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            var imageH1Parameter = imageH1 != null ?
                new ObjectParameter("imageH1", imageH1) :
                new ObjectParameter("imageH1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Photo_UpdateImageH1", photoIdParameter, imageH1Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Photo_UpdateImageH2(Nullable<System.Guid> photoId, string imageH2)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            var imageH2Parameter = imageH2 != null ?
                new ObjectParameter("imageH2", imageH2) :
                new ObjectParameter("imageH2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Photo_UpdateImageH2", photoIdParameter, imageH2Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Photo_UpdateImageW1(Nullable<System.Guid> photoId, string imageW1)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(System.Guid));
    
            var imageW1Parameter = imageW1 != null ?
                new ObjectParameter("imageW1", imageW1) :
                new ObjectParameter("imageW1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Photo_UpdateImageW1", photoIdParameter, imageW1Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_HashTag_IncrViews(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_HashTag_IncrViews", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pb_Product_IncrViews(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pb_Product_IncrViews", idParameter);
        }
    }
}
